fix: pin eslint-plugin-n to ^15.7 to support node 14
adobe/aio-lib-target pull request #80
Opened 2023-09-12 15:01 UTC by MichaelGoberling

## Description

Version `^16.0` of `eslint-plugin-n` doesn't support Node 14, but `aio` still does. Pin to `^15.7` for now

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-09-12 15:29 UTC, MichaelGoberling commented
Tests failing [here](https://github.com/adobe/aio-lib-target/actions/runs/6161279638/job/16720165525?pr=80#step:7:20) because `fetch-mock` package can't find `node-fetch`. Seems we need to add this under `devDependencies`?

Old issue on `fetch-mock` saying this is the case: https://github.com/wheresrhys/fetch-mock/issues/406#issuecomment-450386239

2023-09-13 02:29 UTC, shazron requested changes

2023-09-13 02:29 UTC, shazron commented on package.json
> +    "node-fetch": "^2.6.0",
I don't think this is needed

2023-09-13 03:35 UTC, shazron commented on package.json
> +    "node-fetch": "^2.6.0",
ok I should read the comments first lol. Will investigate.

2023-09-13 03:49 UTC, shazron commented
> Tests failing [here](https://github.com/adobe/aio-lib-target/actions/runs/6161279638/job/16720165525?pr=80#step:7:20) because `fetch-mock` package can't find `node-fetch`. Seems we need to add this under `devDependencies`?
> 
> Old issue on `fetch-mock` saying this is the case: [wheresrhys/fetch-mock#406 (comment)](https://github.com/wheresrhys/fetch-mock/issues/406#issuecomment-450386239)

Seems like the daily runs were disabled since a year ago, so we didn't catch this. What perplexes me is 5 days ago, this commit was all green https://github.com/adobe/aio-lib-target/commit/69027a2ea6862f84d14f17c388dbbc329b383035 and fetch-mock was last published 3 years ago, so not sure what is changed.

Will change my review to approved, since this is what is expected for fetch-mock

2023-09-13 03:49 UTC, shazron approved these changes

2023-09-13 03:50 UTC, merged